FROM your_image_that_you_are_writing_your_code_in

WORKDIR /app


COPY . .

RUN install any packages you need

VOLUME /data

ENTRYPOINT ["the", "command", "that", "you", "use", "to", "init", "your", "app"]